create table if not exists business_cards(
id bigint generated by default as identity primary key,
created_at timestamptz default now(),
name text,
company text,
phone text,
email text,
image_url text,
memo text
);